= Muhammad Syabil Bin Mohamed Sazali - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: AddressBook - Level 4
Schedubook is used by students to better manage and visualize their days by organizing their meetings. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 9 kLoC.
This project is a product of the module, Software Engineering, CS2103T, in NUS. _ScheduBook_ is proudly developed by my team based on https://github.com/se-edu/addressbook-level4[AddressBook(Level4)], and by https://se-edu.github.io/[SE-EDU] team, whose initial address book application was created to be used for teaching Software Engineering principles.


*Code contributed*: [https://github.com/CS2103AUG2017-T09-B2/main/blob/master/collated/main/Syabil.md[Functional code]] [https://github.com/CS2103AUG2017-T09-B2/main/blob/master/collated/test/Syabil.md[Test code]] {give links to collated code files}

=== Enhancement Added: DeleteMeeting

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=deletemeeting]

#End of Extract#

---

==== Justification

There is a need for students to properly plan their important meetings. After the addmeeting function done by group mate, Nelson, the deletemeeting feature allows student
to delete meetings with existing contacts and to get rid of any unnecessary meetings.


==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=deletemeeting]

#End of Extract#

---

=== Enhancement Proposed: Add delete multiple meetings

Allows user to delete multiple meetings at once whenever the user wants to remove multiple meetings that are unnecessary.

=== Enhancement Proposed: Delete a specific contact in group meetings

Allows user to delete a specific contact in group meetings in a case where he/she were not attending this group meeting after it has been added to Schedubook.


=== Enhancement Added: FindMeeting

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=findmeeting]

#End of Extract#

---

==== Justification

It serves as a navigation command which helps the user to sift through all of his/her meetings to narrow down and display only the relevant meetings.


==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=findmeeting]

#End of Extract#

---

=== Enhancement Proposed: Add find person on Twitter/Facebook

Allows user to find the person he is meeting with for his twitter or facebook account to get to know the contact more.

=== Enhancement Added: ListMeeting

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=listmeeting]

#End of Extract#

---

==== Justification

This feature is to list down all the meetings that has been added into one single list which is arranged in order of timing.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=listmeeting]

#End of Extract#

---

=== Enhancement Proposed: Add list meeting location feature

Allows the user to list all meetings at the same location so that he/she can better visualize how many times he/she has to go there for meetings.

=== Other contributions

* Show total contacts in status bar (Pull requests https://github.com/CS2103AUG2017-T09-B2/main/pull/42)
* Added splash page as a home page to the app (Pull requests https://github.com/CS2103AUG2017-T09-B2/main/pull/118)
